'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property dpdVidQualityFSG() As Integer
            Get
                Return CType(Me("dpdVidQualityFSG"),Integer)
            End Get
            Set
                Me("dpdVidQualityFSG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dpdVidFormatFSG() As Integer
            Get
                Return CType(Me("dpdVidFormatFSG"),Integer)
            End Get
            Set
                Me("dpdVidFormatFSG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property switchAppearence_AsDefaultFSG() As Boolean
            Get
                Return CType(Me("switchAppearence_AsDefaultFSG"),Boolean)
            End Get
            Set
                Me("switchAppearence_AsDefaultFSG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSA_PasteURLs() As Boolean
            Get
                Return CType(Me("ckbFSA_PasteURLs"),Boolean)
            End Get
            Set
                Me("ckbFSA_PasteURLs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSA_PreviewVid() As Boolean
            Get
                Return CType(Me("ckbFSA_PreviewVid"),Boolean)
            End Get
            Set
                Me("ckbFSA_PreviewVid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSA_AddHistory() As Boolean
            Get
                Return CType(Me("ckbFSA_AddHistory"),Boolean)
            End Get
            Set
                Me("ckbFSA_AddHistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSA_AutoCkUpdates() As Boolean
            Get
                Return CType(Me("ckbFSA_AutoCkUpdates"),Boolean)
            End Get
            Set
                Me("ckbFSA_AutoCkUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSA_AutoSaveSets() As Boolean
            Get
                Return CType(Me("ckbFSA_AutoSaveSets"),Boolean)
            End Get
            Set
                Me("ckbFSA_AutoSaveSets") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property switchOffDownloadDoneFSA() As Boolean
            Get
                Return CType(Me("switchOffDownloadDoneFSA"),Boolean)
            End Get
            Set
                Me("switchOffDownloadDoneFSA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property switchSoundEnableFSA() As Boolean
            Get
                Return CType(Me("switchSoundEnableFSA"),Boolean)
            End Get
            Set
                Me("switchSoundEnableFSA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtFileNameFSF() As String
            Get
                Return CType(Me("txtFileNameFSF"),String)
            End Get
            Set
                Me("txtFileNameFSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property switchOriginal_YoutubeTileFSF() As Boolean
            Get
                Return CType(Me("switchOriginal_YoutubeTileFSF"),Boolean)
            End Get
            Set
                Me("switchOriginal_YoutubeTileFSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtFilePathFSO() As String
            Get
                Return CType(Me("txtFilePathFSO"),String)
            End Get
            Set
                Me("txtFilePathFSO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSO_KeepOrig_FileName() As Boolean
            Get
                Return CType(Me("ckbFSO_KeepOrig_FileName"),Boolean)
            End Get
            Set
                Me("ckbFSO_KeepOrig_FileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSO_Overwrite_IfExist() As Boolean
            Get
                Return CType(Me("ckbFSO_Overwrite_IfExist"),Boolean)
            End Get
            Set
                Me("ckbFSO_Overwrite_IfExist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckbFSO_SaveVidThumbnail() As Boolean
            Get
                Return CType(Me("ckbFSO_SaveVidThumbnail"),Boolean)
            End Get
            Set
                Me("ckbFSO_SaveVidThumbnail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cbbQuality_strFD() As String
            Get
                Return CType(Me("cbbQuality_strFD"),String)
            End Get
            Set
                Me("cbbQuality_strFD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cbbFormat_strFD() As String
            Get
                Return CType(Me("cbbFormat_strFD"),String)
            End Get
            Set
                Me("cbbFormat_strFD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtURL_varFD() As String
            Get
                Return CType(Me("txtURL_varFD"),String)
            End Get
            Set
                Me("txtURL_varFD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property lblCurrentStatus_varFTMD() As String
            Get
                Return CType(Me("lblCurrentStatus_varFTMD"),String)
            End Get
            Set
                Me("lblCurrentStatus_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lblLastDownFTMD_var() As String
            Get
                Return CType(Me("lblLastDownFTMD_var"),String)
            End Get
            Set
                Me("lblLastDownFTMD_var") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lblVidSize_varFTMD() As String
            Get
                Return CType(Me("lblVidSize_varFTMD"),String)
            End Get
            Set
                Me("lblVidSize_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lblVidName_varFTMD() As String
            Get
                Return CType(Me("lblVidName_varFTMD"),String)
            End Get
            Set
                Me("lblVidName_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lblVidFormat_varFTMD() As String
            Get
                Return CType(Me("lblVidFormat_varFTMD"),String)
            End Get
            Set
                Me("lblVidFormat_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lblProgressValueFTMD_var() As String
            Get
                Return CType(Me("lblProgressValueFTMD_var"),String)
            End Get
            Set
                Me("lblProgressValueFTMD_var") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property gpgbDownloadProgressFTMD() As Integer
            Get
                Return CType(Me("gpgbDownloadProgressFTMD"),Integer)
            End Get
            Set
                Me("gpgbDownloadProgressFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_ftmd_lblVidName_varFTMD() As String
            Get
                Return CType(Me("ui_ftmd_lblVidName_varFTMD"),String)
            End Get
            Set
                Me("ui_ftmd_lblVidName_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_ftmd_lblVidSize_varFTMD() As String
            Get
                Return CType(Me("ui_ftmd_lblVidSize_varFTMD"),String)
            End Get
            Set
                Me("ui_ftmd_lblVidSize_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_ftmd_lblVidFormat_varFTMD() As String
            Get
                Return CType(Me("ui_ftmd_lblVidFormat_varFTMD"),String)
            End Get
            Set
                Me("ui_ftmd_lblVidFormat_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_ftmd_lblLastDownFTMD_var() As String
            Get
                Return CType(Me("ui_ftmd_lblLastDownFTMD_var"),String)
            End Get
            Set
                Me("ui_ftmd_lblLastDownFTMD_var") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_ftmd_lblCurrentStatus_varFTMD() As String
            Get
                Return CType(Me("ui_ftmd_lblCurrentStatus_varFTMD"),String)
            End Get
            Set
                Me("ui_ftmd_lblCurrentStatus_varFTMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_ftmd_lblProgressValueFTMD_var() As String
            Get
                Return CType(Me("ui_ftmd_lblProgressValueFTMD_var"),String)
            End Get
            Set
                Me("ui_ftmd_lblProgressValueFTMD_var") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FP_txtURL_varFD_pass() As String
            Get
                Return CType(Me("FP_txtURL_varFD_pass"),String)
            End Get
            Set
                Me("FP_txtURL_varFD_pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property direct_prev_link() As String
            Get
                Return CType(Me("direct_prev_link"),String)
            End Get
            Set
                Me("direct_prev_link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_frm_varDownSize() As String
            Get
                Return CType(Me("ui_frm_varDownSize"),String)
            End Get
            Set
                Me("ui_frm_varDownSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property History() As Integer
            Get
                Return CType(Me("History"),Integer)
            End Get
            Set
                Me("History") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_log() As String
            Get
                Return CType(Me("ui_log"),String)
            End Get
            Set
                Me("ui_log") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property switchHomeTutoMain() As Boolean
            Get
                Return CType(Me("switchHomeTutoMain"),Boolean)
            End Get
            Set
                Me("switchHomeTutoMain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property switchHomeTutoFSG() As Boolean
            Get
                Return CType(Me("switchHomeTutoFSG"),Boolean)
            End Get
            Set
                Me("switchHomeTutoFSG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_lbl_frmPlay_varVidName() As String
            Get
                Return CType(Me("ui_lbl_frmPlay_varVidName"),String)
            End Get
            Set
                Me("ui_lbl_frmPlay_varVidName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ui_lbl_frmPlay_varVidPath() As String
            Get
                Return CType(Me("ui_lbl_frmPlay_varVidPath"),String)
            End Get
            Set
                Me("ui_lbl_frmPlay_varVidPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ui_lbl_frmPlay_varProgressBar() As Integer
            Get
                Return CType(Me("ui_lbl_frmPlay_varProgressBar"),Integer)
            End Get
            Set
                Me("ui_lbl_frmPlay_varProgressBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ui_feedbacks() As Boolean
            Get
                Return CType(Me("ui_feedbacks"),Boolean)
            End Get
            Set
                Me("ui_feedbacks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ui_premiumfeatures() As Boolean
            Get
                Return CType(Me("ui_premiumfeatures"),Boolean)
            End Get
            Set
                Me("ui_premiumfeatures") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MySoft_YouTube_Downloader.My.MySettings
            Get
                Return Global.MySoft_YouTube_Downloader.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
